### ISSUE TITLE
Custom Fonts Not Loading

### ISSUE THREAD

**Issue by philsinatra** [SeamusACD/SDDesign.tech#1]
The CSS for your custom fonts needs an adjustment to fix a rendering bug:

<a href="https://github.com/SeamusACD/SDDesign.tech/blob/619f3b6b312482c198aa2220830a4e4a67fbd9dc/local_html/source/html/style.css#L3-L29" target="_blank">https://github.com/SeamusACD/SDDesign.tech/blob/619f3b6b312482c198aa2220830a4e4a67fbd9dc/local_html/source/html/style.css#L3-L29</a>

As an example, look at the first declaration:

```css
@font-face {
  font-family: 'AvenirNextLTW01RegularRegular';
  src: url('/fonts/AvenirNextLTW01RegularRegular.eot?#iefix') format('embedded-opentype'),  
  	   url('AvenirNextLTW01RegularRegular.woff') format('woff'), 
  	   url('AvenirNextLTW01RegularRegular.ttf')  format('truetype'), 
  	   url('AvenirNextLTW01RegularRegular.svg#AvenirNextLTW01RegularRegular') format('svg');
}
```

The `src` attribute has four `url` values, you updated the path to include the location of your font files in the first `url` (`/fonts/`) but the other three do not include the updated path, and therefore, will not work.

```css
 src: url('/fonts/AvenirNextLTW01RegularRegular.eot?#iefix') format('embedded-opentype'),  
  	   url('AvenirNextLTW01RegularRegular.woff') format('woff'), 
 ```

This might not be an obvious bug on your computer, because you more than likely have the fonts installed on your system, and so they load okay. But on a system that does not have these fonts installed globally, the custom font files aren't found and therefore can't load, leaving you with your fallbacks in place and a bunch of validation errors.

![screen shot 2016-12-08 at 7 46 11 am](https://cloud.githubusercontent.com/assets/1465808/21010505/6eee543e-bd1a-11e6-97a5-a87a08b26ee3.png)
